/** Généré depuis docs/tuto-images-jarvis.md — ne pas éditer à la main. */
export type SetupGuideStep = { id: string; section: string; text: string; image: string };

export const SETUP_GUIDE_STEPS: SetupGuideStep[] = [
  { id: "1.1", section: "1. Installer Jarvis", text: "Télécharge `Jarvis-Setup-5.0.17.exe` sur GitHub (release v5.0.17).", image: "01-telecharger-exe.png" },
  { id: "1.2", section: "1. Installer Jarvis", text: "Double-clique sur l’installateur.", image: "02-double-clic-installateur.png" },
  { id: "1.3", section: "1. Installer Jarvis", text: "Clique **Informations complémentaires** si SmartScreen s’affiche.", image: "03-smartscreen-infos.png" },
  { id: "1.4", section: "1. Installer Jarvis", text: "Clique **Exécuter quand même**.", image: "04-smartscreen-executer.png" },
  { id: "1.5", section: "1. Installer Jarvis", text: "Attends : la fenêtre Jarvis s’ouvre.", image: "05-installation-terminee.png" },
  { id: "1.6", section: "1. Installer Jarvis", text: "Appuie sur **Ctrl + Espace** pour parler à Jarvis.", image: "06-raccourci-ctrl-espace.png" },
  { id: "1.7", section: "1. Installer Jarvis", text: "Ouvre **Réglages** (engrenage).", image: "07-ouvrir-reglages.png" },
  { id: "1.8", section: "1. Installer Jarvis", text: "Onglet **Mises à jour** → **Vérifier les mises à jour**.", image: "08-mises-a-jour.png" },
  { id: "2.1", section: "2. Ollama", text: "Installe Ollama depuis [ollama.com/download](https://ollama.com/download).", image: "09-ollama-download.png" },
  { id: "2.2", section: "2. Ollama", text: "Lance `ollama pull qwen2.5:3b` dans PowerShell.", image: "10-ollama-pull.png" },
  { id: "2.3", section: "2. Ollama", text: "Ouvre `http://127.0.0.1:11434` dans le navigateur.", image: "11-ollama-api.png" },
  { id: "2.4", section: "2. Ollama", text: "Dans Jarvis, ouvre **Réglages**.", image: "12-jarvis-reglages-ollama.png" },
  { id: "2.5", section: "2. Ollama", text: "Clique l’onglet **Modèle IA**.", image: "13-onglet-modele-ia.png" },
  { id: "2.6", section: "2. Ollama", text: "Choisis **Ollama (local, gratuit)**.", image: "14-fournisseur-ollama.png" },
  { id: "2.7", section: "2. Ollama", text: "Garde l’URL `http://127.0.0.1:11434` → **Actualiser**.", image: "15-url-actualiser.png" },
  { id: "2.8", section: "2. Ollama", text: "Sélectionne **qwen2.5:3b** dans **Modèle installé**.", image: "16-modele-qwen.png" },
  { id: "2.9", section: "2. Ollama", text: "Clique **Tester** et attends OK.", image: "17-tester-ollama.png" },
  { id: "2.10", section: "2. Ollama", text: "Clique **Enregistrer**.", image: "18-enregistrer-ollama.png" },
  { id: "3.1", section: "3. Spotify (optionnel)", text: "Ouvre [developer.spotify.com/dashboard](https://developer.spotify.com/dashboard).", image: "19-spotify-dashboard.png" },
  { id: "3.2", section: "3. Spotify (optionnel)", text: "Ajoute la **Redirect URI** `http://127.0.0.1:53124/callback`.", image: "20-spotify-redirect-uri.png" },
  { id: "3.3", section: "3. Spotify (optionnel)", text: "Copie le **Client ID**.", image: "21-spotify-client-id.png" },
  { id: "3.4", section: "3. Spotify (optionnel)", text: "Jarvis → **Réglages** → **Spotify**.", image: "22-jarvis-onglet-spotify.png" },
  { id: "3.5", section: "3. Spotify (optionnel)", text: "Colle dans **Identifiant client (Client ID)**.", image: "23-spotify-coller-id.png" },
  { id: "3.6", section: "3. Spotify (optionnel)", text: "Clique **Se connecter** (navigateur).", image: "24-spotify-connecter.png" },
  { id: "3.7", section: "3. Spotify (optionnel)", text: "Clique **Enregistrer**.", image: "25-spotify-enregistrer.png" },
  { id: "4.1", section: "4. Google (optionnel)", text: "Crée un projet **Jarvis** sur Google Cloud.", image: "26-google-projet.png" },
  { id: "4.2", section: "4. Google (optionnel)", text: "Active Gmail, Calendar, Drive, Docs, Sheets.", image: "27-google-activer-api.png" },
  { id: "4.3", section: "4. Google (optionnel)", text: "**Google Auth Platform** → **Commencer**.", image: "28-google-consentement.png" },
  { id: "4.4", section: "4. Google (optionnel)", text: "**Audience** : **Externe**.", image: "29-google-audience-externe.png" },
  { id: "4.5", section: "4. Google (optionnel)", text: "**Ajouter des utilisateurs** → ton Gmail → **Enregistrer**.", image: "30-google-utilisateurs-test.png" },
  { id: "4.6", section: "4. Google (optionnel)", text: "**Clients** → **Créer un client**.", image: "31-google-creer-client.png" },
  { id: "4.7", section: "4. Google (optionnel)", text: "Type **Application de bureau** → **Créer**.", image: "32-google-application-bureau.png" },
  { id: "4.8", section: "4. Google (optionnel)", text: "Copie **Identifiant client** et **Secret client** (`GOCSPX-…`). Redirection locale : `http://127.0.0.1:53125/callback`.", image: "33-google-copier-secrets.png" },
  { id: "4.9", section: "4. Google (optionnel)", text: "Jarvis → **Réglages** → **Google**.", image: "34-jarvis-onglet-google.png" },
  { id: "4.10", section: "4. Google (optionnel)", text: "Colle **Identifiant client (Client ID)** et **Secret client**.", image: "35-google-coller-champs.png" },
  { id: "4.11", section: "4. Google (optionnel)", text: "Choisis **Accès demandé**.", image: "36-google-acces.png" },
  { id: "4.12", section: "4. Google (optionnel)", text: "Clique **Se connecter**.", image: "37-google-connecter.png" },
  { id: "4.13", section: "4. Google (optionnel)", text: "Si besoin, clique **Continuer** (mode Test).", image: "38-google-continuer.png" },
  { id: "4.14", section: "4. Google (optionnel)", text: "Clique **Enregistrer**.", image: "39-google-enregistrer.png" },
];
